baseURL = 'https://blog.take4s5i.dev/'
languageCode = 'ja-jp'
title = '6 bits blog'
theme = 'cactus'
googleAnalytics = 'G-EL27BW0FWC'
timeZone = 'Asia/Tokyo'

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

# [[menu.main]]
# name = "About"
# url = "/about"
# weight = 4

[params]
  showAllPostsOnHomePage = true
